---  

 #By this code we can install Nodejs in different OS (RHEL,CentOS,Amazon,Ubuntu 14.0). In ubuntu 16.04  python is requried.


#downloaded the tar file from the nodejs official website
- name: wget node
  get_url: url=http://nodejs.org/dist/v{{ version }}/node-v{{ version }}-linux-x64.tar.gz  dest=/tmp/node-v{{ version }}.tar.gz
  
#untar the file which we downloaded  
- name: untar
  command: tar -xvf /tmp/node-v{{version}}.tar.gz -C /tmp 

#moving the extract file   
  
- name: moving
  command: mv /tmp/node-v{{version}}-linux-x64 /opt/nodejs-v{{version}}
  
#moving the file from source to destination  
                                        
- name: moving files
  file: src=/opt/nodejs-v{{ version }}/bin/node path=/usr/bin/node state=link
