---
# Installing open-jdk 
- name: Install Java 1.7
  yum: name=java-1.7.0-openjdk state=present

# creating a group for tomcat to manage tomcat web server
- name: add group "tomcat_group"
  group: name={{ tomcat_group }}

# Creating a user for tomcat and adding to tomcar group to manager tomcat web server
- name: add user "tomcat_user"
  user: name={{ tomcat_user}} group={{ tomcat_group }} home=/usr/share/tomcat createhome=no
 
# Downloading the tomcat tar file  
- name: Download Tomcat
  get_url: url={{ tomcat_tar_file }} dest=/opt/apache-tomcat-{{ tomcat_version }}.tar.gz

# Extracting tar file into directory
- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-{{ tomcat_version }}.tar.gz -C /opt/ creates=/opt/apache-tomcat-{{ tomcat_version }}

# creating a symbolic link to the another directory
- name: Symlink install directory
  file: src=/opt/apache-tomcat-{{ tomcat_version }} path=/usr/share/tomcat state=link

# changing the ownership to tomcat_user for the tomcat home directory
- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

# copying configured tomcat server file to tomcat configuration directory
- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

# copying the configured tomcat users file to tomcat configuration directory
- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

# Copying the init script for tomcat operations
- name: Install Tomcat init script
  template: src=amazon-init.sh dest=/etc/init.d/tomcat mode=0755

# checks whether tomcat server has started
- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

# Wait untill the tomcat server to start
- name: wait for tomcat to start
  wait_for: port={{http_port}}