---
- name: Install Java 1.7
  yum: name=java-1.{{ java_version }}-openjdk state=present

# creating the group for the managing tomcat server
- name: add group "tomcat_group"
  group: name={{ tomcat_group }}

# creating a user for managing tomcat server
- name: add user "tomcat_user"
  user: name={{ tomcat_user }} group={{ tomcat_group }} home=/usr/share/tomcat createhome=no

# Downloading tomcat tar ball and saving in the local directory
- name: Download Tomcat
  get_url: url={{ tomcat_tar_file }} dest=/opt/apache-tomcat-{{ tomcat_version }}.tar.gz

# Extracting the tar ball 
- name: Extract archive tomcat tar file
  command: /bin/tar xvf /opt/apache-tomcat-{{ tomcat_version }}.tar.gz -C /opt/ creates=/opt/apache-tomcat-{{ tomcat_version }}

# Changing the ownership to tomcat_user for tomcat home folder 
- name: Change ownership of Tomcat installation
  file: path=/opt/apache-tomcat-{{ tomcat_version }} owner={{ tomcat_user }} group={{ tomcat_group }} state=directory recurse=yes

# copying configured tomcat server file to tomcat configuration folder
- name: Configure Tomcat server
  template: src=server.xml dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/
  notify: restart tomcat

# copying configured tomcat user file to tomcat configuration folder
- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/   
  notify: restart tomcat

# Copying systemd script to manage tomcat operations
- name: Install Tomcat systemd script
  template: src=redhat-init.sh dest=/etc/systemd/system/tomcat.service mode=0755

# making sure the tomcat server is started
- name: Make sure the tomcat is started
  service: name=tomcat state=started enabled=yes

# Inserting firewall rule for allow http_port for tomcat
- name: Insert firewalld rule for tomcat http port
  firewalld: port={{ http_port }}/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

# Inserting firewall rule for allow https_port for tomcat
- name: Insert firewalld rule for tomcat https port
  firewalld: port={{ https_port }}/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'Redhat' and ansible_distribution_major_version == '7'"

# Waits untill the tomcat server starts
- name: Wait for tomcat to start
  wait_for: port={{http_port}}
